import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";

import Link from "next/link";
import ThemeSwitcher from "./components/ThemeSwitcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pokemon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <header className="py-8">
            <nav className="container flex items-center justify-between">
              <ul>
                <li>
                  <Link href="/" className="text-md font-semibold">
                    Home
                  </Link>
                </li>
              </ul>
              <ThemeSwitcher />
            </nav>
          </header>

          <main className="flex m-h-screen flex-col container mt-4">
            <h2 className="text-xl md:text-2xl font-bold">Pokemon Finder</h2>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
